### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by strteamservidores** [WardPearce/SourceQueryBot#10]
Any help?

`  File "run.py", line 1, in <module>
    from SourceQueryBot import SourceQueryBot
  File "/root/Tessste/SourceQueryBot/__init__.py", line 26
    def __init__(self, catagories: list,
                                 ^
SyntaxError: invalid syntax
`

**Comment by WardPearce** [comment]
What python version are you using?

**Comment by WardPearce** [comment]
I'm closing this issue, reopen it if this didn't fix it.
